### ISSUE TITLE
Having trouble working with TypeScript components

### ISSUE THREAD

**Issue by SoftHai** [webcodesk/wcd-empty-pwa-ts#1]
Hi,
I'm new to Webcodesk and want to start to play with it because I see a huge potential in your project.
I installed Webcodesk and selected this TypeScript template.
I added a first very simple component. 
```
import React from 'react';

class ThreePanelScreen extends React.Component {

    render() {
        return <div>Demo</div>
    }
}

export default ThreePanelScreen;
```
The component shows up in the Frontend (Left side).
When I select the component, I get the following error in the preview:
`./src/app/indices/userComponents.js
Module not found: Can't resolve 'usr/Layout/ThreePanelScreen.comp' in 'C:\Configit\OwnGit\Heiko's Playground\Webcodesk Playground\Playground\src\app\indices'`

Don't know what I doing wrong.
Could you help me. 
Thanks

**Comment by ipselon** [comment]
Hi,

could you show me the Webpack server log here? You can find it on the top-left menu.

<img width="449" alt="Screenshot 2020-03-26 at 09 00 39" src="https://user-images.githubusercontent.com/11865795/77619205-65849800-6f40-11ea-9672-8d67dccd25b7.png">

**Comment by SoftHai** [comment]
Sure, here is the Server Log:
![image](https://user-images.githubusercontent.com/5662304/77704765-1bda9280-6fbe-11ea-994e-56570796b2bf.png)
Don't shows so much more details, isn't it?

**Comment by ipselon** [comment]
@SoftHai,

Thank you.

> Don't know if it is relevant but the component is a tsx file.

That's the correct file extension, and it should not make any issue.

Here are my suggestions:

1. The `C:\Configit\OwnGit\Heiko's Playground\Webcodesk Playground\Playground\src\app\indices` path looks suspicious because of spaces and single quote character. Webpack may not recognize files in such a path on Windows. Would you mind to try run Webcodesk in the directory with a path that does not include spaces?

2. If the 1st step will not help, I'd like to take a look at the source of your app. Would you mind to add the app source code into a repo on github?

**Comment by SoftHai** [comment]
Hi,
I now tested it with a different folder structure but still facing the same issue:
```
./src/app/indices/userComponents.js
Module not found: Can't resolve 'usr/Layout/ThreePanelScreen.comp' in 'c:\Playground\Playground\src\app\indices'
```

So what have I done:
- Installed Webcodesk via npx: ```npx @webcodesk/install-webcodesk Playground```
- Start the Server
- In the application I selected the TypeScript Start Set
- Added a new file in usr/layout/threePanelScreen .comp.tsx with the following code
```
import React from 'react';

class threePanelScreen extends React.Component {

    render() {
        return <div>Demo</div>
    }
}

export default threePanelScreen;
```
- Refresh the Website
- Select the component in Preview
- see the error

[MyCode.zip](https://github.com/webcodesk/wcd-empty-pwa-ts/files/4395774/MyCode.zip)

Any step I maybe missed to do?
Thanks for your support.

**Comment by ipselon** [comment]
@SoftHai,

Thank you for your patient. I appreciate your help. 

I found out that I had forgotten to add the base URL into the `tsconfig.json`.

So, please add the following line into `tsconfig.json` and restart wcd:

```
{
  "compilerOptions": {
    "baseUrl": "./src",
    ....
}
```


BTW, avoid names that start with a small character. It should start with uppercase char: `ThreePanelScreen`.

**Comment by SoftHai** [comment]
Hi,
many thanks for your help. This solves the error.
Please add it to the default template.

Regarding the naming: this was just playing around with different names to check if they make any difference. Typically they start with an upper case.

I will let you know, in case I have further issues or maybe created something nice with your tool.
Looking forward to explore you project.

**Comment by ipselon** [comment]
@SoftHai,

> I will let you know, in case I have further issues or maybe created something nice with your tool.

I and my colleague are working on a bundle that includes the Web app template with many enterprise-level React components. We want to make many ready-to-use components based on Microsoft [Office UI Fabric React](https://developer.microsoft.com/en-us/fluentui#/controls/web) (now they call it Fluet UI).

The idea is to create two bundles: one for free usage with a small number of components, and another one with many components for commercial usage ($150 - $200) for the bundle.

We thought that we can sell the bundle to companies that want to bootstrap Web apps with components and Webcodesk.

If you see a potential in this idea, I'd be glad if you join us. However, we work together for free now in our spare time. But if we put more efforts we can finish the bundle with the first phase components in 1-1.5 months.

If you have questions about how it is going to be, please let me know - I'll be happy to answer you.
